meta_product_name: "Space Station"
meta_title: "Space Station : Source the World's Fashion Designers"
meta_description: "Disover and source the world's most creative and exotic fashion designers through our b2b wholesale platform."
meta_image: "space_station.png"                       # should exist in `app/assets/images/`
twitter_account: "@pgidahuss"   # required for Twitter Cards
